name: Vérification MonitoringRefs quotidienne

on:
  schedule:
    - cron: '0 6 * * *'  # Exécution tous les jours à 6h UTC
  workflow_dispatch:     # Permet de déclencher manuellement l’action si besoin

jobs:
  check-monitoringrefs:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Installer les dépendances (si besoin)
        run: npm install

      - name: Lancer le script de vérification
        run: node checkMonitoringRefs.js

      - name: Envoyer une alerte Slack (si échec)
        if: failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "❗ La vérification des MonitoringRefs a échoué : voir les logs sur GitHub Actions."
